server:
  port: 9400
spring:
  application:
    name: service-admin-server
  security:
    user:
      name: "user"          #这里在AdminServer端设置了账号和密码
      password: "password"
  rabbitmq:
    host: server1
    port: 5672
    username: guest
    password: guest
feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"